# ns1
server:
    rundir: "/run/knot"
    user: knot:knot
    listen: [ 0.0.0.0@53, ::@53 ]

log:
  - target: syslog
    any: info

database:
    storage: "/var/lib/knot"

include: /etc/knot/keys.conf

remote:
  - id: ns2
    address: [ 185.194.142.111, 2a03:4000:1c:32:d884:36ff:fedd:6dea ]
    key: xfer-key
    via: [ 142.248.111.119, 2602:f761:40:ffff:be24:11ff:fecc:3feb ]

acl:
  - id: transfer-to-ns2
    address: [ 185.194.142.111, 2a03:4000:1c:32:d884:36ff:fedd:6dea ]
    key: xfer-key
    action: transfer

mod-rrl:
  - id: default
    rate-limit: 50
    slip: 2

template:
  - id: default
    global-module: mod-rrl/default

policy:
  - id: ed25519
    algorithm: ed25519
    zsk-lifetime: 30d
    ksk-lifetime: 0
    nsec3: on
    nsec3-iterations: 0
    nsec3-salt-length: 0

zone:
  - domain: toprakkilic.com
    storage: "/var/lib/knot/zones"
    file: toprakkilic.com.zone
    dnssec-signing: on
    dnssec-policy: ed25519
    zonefile-load: difference-no-serial
    zonefile-sync: -1
    journal-content: all
    serial-policy: dateserial
    semantic-checks: on
    notify: ns2
    acl: transfer-to-ns2