include: /etc/knot/keys.conf

server:
    rundir: "/run/knot"
    user: knot:knot
    listen: [ 0.0.0.0@53, ::@53 ]

log:
  - target: syslog
    any: info

database:
    storage: "/var/lib/knot"

policy:
  - id: ed25519
    algorithm: ed25519
    zsk-lifetime: 30d
    ksk-lifetime: 0
    nsec3: on
    nsec3-iterations: 0
    nsec3-salt-length: 0

zone:
  - domain: toprakkilic.com
    storage: "/var/lib/knot/zones"
    file: toprakkilic.com.zone
    dnssec-signing: on
    dnssec-policy: ed25519
    zonefile-load: difference-no-serial
    zonefile-sync: -1
    journal-content: all
    serial-policy: dateserial
    semantic-checks: on

# zone edit
#   kzonecheck -o toprakkilic.com /var/lib/knot/zones/toprakkilic.com.zone
#   knotc zone-reload toprakkilic.com

# DS to the registrar (first time and KSK rollover)
#   keymgr toprakkilic.com. ds