# ns2

server:
    rundir: "/run/knot"
    user: knot:knot
    listen: [ 0.0.0.0@53, ::@53 ]

log:
  - target: syslog
    any: info

database:
    storage: "/var/lib/knot"

include: /etc/knot/keys.conf

remote:
  - id: ns1
    address: [ 142.248.111.119, 2602:f761:40:ffff:be24:11ff:fecc:3feb ]
    key: xfer-key

acl:
  - id: notify-from-ns1
    address: [ 142.248.111.119, 2602:f761:40:ffff:be24:11ff:fecc:3feb ]
    key: xfer-key
    action: notify

mod-rrl:
  - id: default
    rate-limit: 50
    slip: 2

template:
  - id: default
    global-module: mod-rrl/default

zone:
  - domain: toprakkilic.com
    master: ns1
    acl: notify-from-ns1
    storage: "/var/lib/knot/zones"
    file: toprakkilic.com.zone
    zonefile-sync: 0
    journal-content: changes
    semantic-checks: on